# Generated by Django 5.0.1 on 2024-03-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_has',
            new_name='password_hash',
        ),
    ]
